# Generated by Django 2.0.3 on 2018-05-11 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityname', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('rating', models.IntegerField()),
                ('photo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryname', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('arrivalData', models.DateTimeField()),
                ('departureData', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default='', max_length=32)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_province', to='mymodel.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomName', models.CharField(max_length=32)),
                ('roomType', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=100)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('numOfPerson', models.IntegerField()),
                ('numOfBed', models.IntegerField()),
                ('numOfBathroom', models.IntegerField()),
                ('specificAddress', models.CharField(max_length=32)),
                ('otherOption', models.CharField(default=None, max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('photoDir', models.CharField(default=None, max_length=32)),
                ('rating', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_room', to='mymodel.City')),
                ('contry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_room', to='mymodel.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(default='', max_length=32)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_town', to='mymodel.City')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('paypassword', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_rooms', to='mymodel.User'),
        ),
        migrations.AddField(
            model_name='room',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_room', to='mymodel.Province'),
        ),
        migrations.AddField(
            model_name='room',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_room', to='mymodel.Town'),
        ),
        migrations.AddField(
            model_name='order',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_order', to='mymodel.Room'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to='mymodel.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_comments', to='mymodel.Room'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='mymodel.User'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_city', to='mymodel.Province'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('user', 'room')},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('user', 'room')},
        ),
    ]
