# Generated by Django 2.0.3 on 2018-05-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0002_auto_20180512_2351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='photoDir',
        ),
        migrations.AddField(
            model_name='room',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo3',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo4',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo5',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo6',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo7',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo8',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo9',
            field=models.ImageField(blank=True, upload_to='room/'),
        ),
    ]
