# Generated by Django 2.0.3 on 2018-05-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0003_auto_20180513_0037'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
    ]
