# Generated by Django 2.0.3 on 2018-05-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0004_auto_20180513_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='numOfBathroom',
        ),
        migrations.RemoveField(
            model_name='room',
            name='numOfBed',
        ),
        migrations.RemoveField(
            model_name='room',
            name='numOfPerson',
        ),
        migrations.RemoveField(
            model_name='room',
            name='otherOption',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomName',
        ),
        migrations.RemoveField(
            model_name='room',
            name='roomType',
        ),
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='user',
            name='openid',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='specificAddress',
            field=models.CharField(max_length=60),
        ),
    ]
