# Generated by Django 2.0.3 on 2018-05-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0006_auto_20180527_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='openid',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
