# Generated by Django 2.0.3 on 2018-06-06 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0014_auto_20180606_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_room', to='mymodel.City'),
        ),
        migrations.AlterField(
            model_name='room',
            name='contry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_room', to='mymodel.Country'),
        ),
        migrations.AlterField(
            model_name='room',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='province_room', to='mymodel.Province'),
        ),
        migrations.AlterField(
            model_name='room',
            name='town',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='town_room', to='mymodel.Town'),
        ),
    ]
