# Generated by Django 2.0.3 on 2018-06-07 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0015_auto_20180606_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='arrivalData',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='departureData',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
