# Generated by Django 2.0.3 on 2018-06-09 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymodel', '0016_auto_20180607_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='room/')),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo5',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo6',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo7',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo8',
        ),
        migrations.RemoveField(
            model_name='room',
            name='photo9',
        ),
        migrations.AddField(
            model_name='photo',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_photo', to='mymodel.Room'),
        ),
    ]
